### ISSUE TITLE
Create Project Tasks(issues) identified for milestones for your role

### ISSUE THREAD

**Issue by LeeJMorel** [LeeJMorel/PathKit#26]
**Testers**

- [x] DnA Milestone issues created
- [x] TCC Milestone issues created
- [x] R1 Milestone issues created
- [x] R2 Milestone issues created

**Front-End Dev**

- [x] DnA Milestone issues created
- [x] TCC Milestone issues created
- [x] R1 Milestone issues created
- [x] R2 Milestone issues created

**Back-End Dev**

- [x] DnA Milestone issues created
- [x] TCC Milestone issues created
- [x] R1 Milestone issues created
- [x] R2 Milestone issues created

**Game Dev**

- [x] DnA Milestone issues created
- [x] TCC Milestone issues created
- [x] R1 Milestone issues created
- [x] R2 Milestone issues created

**UX Design**

- [x] DnA Milestone issues created
- [x] TCC Milestone issues created
- [x] R1 Milestone issues created
- [x] R2 Milestone issues created

**Manager**

- [x] DnA Milestone issues created
- [x] TCC Milestone issues created
- [x] R1 Milestone issues created
- [x] R2 Milestone issues created
